# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Long Nguyen Huu
# Jekyll uses description for social network link preview, so keep it for content description,
# and use custom footer more below for footer text
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Long Nguyen Huu aka komehara
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hsandt.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# set up remote_theme for specific commit, so we don't use old stable release
# (commit from 2023-01-09)
remote_theme: jekyll/minima@32468f51758b0b37c2b1f423265d4f29db461b27

# Theme config
author:
  name: Long Nguyen Huu
  email: n.huu.long@gmail.com
minima:
  social_links:
    - platform: itchio
      user_url: "https://komehara.itch.io/"
      title: My games on itch.io
    - platform: github
      user_url: "https://github.com/hsandt"
      title: My GitHub repositories
    - platform: bitbucket
      user_url: "https://bitbucket.org/hsandt/"
      title: My BitBucket repositories
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/3256073/hsandt"
      title: My profile on Stack Overflow
    - platform: twitter
      user_url: "https://twitter.com/n_huulong"
      title: My posts on Twitter
    - platform: mastodon
      user_url: "https://mastodon.gamedev.place/@leyn"
      title: My posts on Mastodon
    - platform: youtube
      user_url: "https://www.youtube.com/channel/UCscc8AXbgMQCjzxsXLVvCsg"
      title: My videos on YouTube
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/huulong/"
      title: My profile on LinkedIn
    - platform: kofi
      user_url: "https://ko-fi.com/komehara"
      title: Donations on Ko-fi

footer: >- # this means to ignore newlines until "baseurl:"
  This website was made with Jekyll and is hosted on GitHub Pages.

# Apply category [category] to all posts under _posts/[category]
# This allows us to add new category sub-folders under _posts, easier than adding a folder [category]/_posts
# to project root, for a cleaner hierarchy.
# Source: https://stackoverflow.com/questions/26676839/how-can-i-create-a-directory-for-each-category-under-posts-in-jekyll
defaults:
  - scope:
      path: "_posts/devlog"
      type: "posts"
    values:
      category: devlog
  - scope:
      path: "_posts/review"
      type: "posts"
    values:
      category: review
# add new [category] here

header_pages:
  - portfolio.markdown
  - blog.markdown
  - writing.markdown
  - comic-strips.markdown
  - resume.markdown

# Collection of portfolio pages, path relative to portfolio/
portfolio_pages:
  - evil-genius-2.markdown
  - hotshot-racing.markdown
  - ghost-recon-breakpoint.markdown
  - guns-gore-and-cannoli-2.markdown

# Collection of comic strip pages, path relative to comic-strips/
comic_strip_pages:
  - welfare.markdown
  - engine.markdown
  - crash-report.markdown
  - confrontation.markdown
  - spellcaster.markdown
  - v-sync.markdown
  - prototype.markdown
  - lens-of-truth.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
